name: CI

on:
  push:
    branches: [ "tesdt" ]
  pull_request:
    branches: [ "tesdt" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: development
      url: ${{ steps.get_release_url.outputs.release_url }}

    steps:
      - name: Set TARGET_BRANCH for push or pull_request
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "TARGET_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
          fi
      - name: Get id and commit hash from status succeeded job on Inspecode
        env:
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
        run: |
          echo "target branch ${{ env.TARGET_BRANCH }}"

