name: Show Grafana URL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  display-url:
    runs-on: ubuntu-latest
    environment: production  # ここで使用する環境を指定します

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display Grafana URL
      run: echo "Grafana URL: ${{ secrets.GRAFANA_URL }}"
