name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: development
      url: ${{ steps.get_release_url.outputs.release_url }}

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set release url
        id: get_release_url
        run: echo "release_url=https://grafana.com" >> $GITHUB_OUTPUT

