name: ci runner device

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}

      - name: Extract runner version
        id: runner_version
        run: |
          echo "Fetching the latest runner version..."
          RUNNER_VERSION=$(curl -s https://github.com/actions/runner/tags/ | grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+" | head -n1 | tr -d 'v')
          echo "Runner version: $RUNNER_VERSION"
          echo "runner_version=$RUNNER_VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: |
            name=ghcr.io/${{ github.repository }}/actions-test
          tags: |
            type=schedule,pattern=daily,enable=true,priority=9
            type=ref,event=pr,prefix=pr-,enable=true,priority=8
            type=ref,event=tag,enable=true,priority=8
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=dev,enable=${{ github.ref != 'refs/heads/main' }},priority=10
            type=semver,pattern={{version}},value=${{ steps.runner_version.outputs.runner_version }}
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: runner/docker
          file: runner/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          # cache-from: type=gha
          # cache-to: type=gha,mode=min